---
# Bad ansible! This playbook is an example of poor/bad practices!
# Bad practices may include:
#
#   Poor formatting and structure
#   Poor use of YAML - but good enough to parse
#   Inconsistent style
#   Incorrect use of modules
#   Poor module choice
#   Unclear names
#   Hard coding / poor use of variables
#   Roles - what are roles?
#   Bare variables
#   No use of handlers
- name: 3.2
  hosts: workstation
  tasks:
  - include_role: 
      name: osp.server

- name: configuration
  hosts: all
  gather_facts: false
  become: true

  tasks:
  - name: enable repos
    template:
      src: ./open_three-tier-app.repo
      dest: /etc/yum.repos.d/open_three-tier-app.repo
      mode: 0644

- name: deploy haproxy
  tags: haproxy
  hosts: frontend
  gather_facts: false
  become: true

  tasks:
  - include_role:
      name: haproxy

- name: deploy tomcat
  hosts: apps
  gather_facts: false
  become: true

  tasks:
  - include_role:
      name: tomcat

- name: deploy postgres
  tags: postgres
  gather_facts: false
  become: true
  hosts: appdbs
  tasks:
  - include_role:
      name: postgres
