---
- name: install postgres
  yum:
    name: postgresql-server
    state: latest

- name: enable apache at boot
  service:
    name: postgresql
    enabled: yes

- name: initialize postgres
  shell: 
    postgresql-setup initdb
  args:
    creates: /var/lib/pgsql/data/PG_VERSION
  # become: true

- name: start postgres
  service:
    name: postgresql.service
    state: started
